### ISSUE TITLE
Smart Smoothing Causes blink-tearing DCS 

### ISSUE THREAD

**Issue by KCrawford100** [mbucchia/Pimax-OpenXR#13]
Pitool v1.0.1.279 Firmware V2.1.255.299  Pimax 8KX
i9900KS 5.2 - 3090 latest Nvidia  PimaxXR - V0.2.0

Smart smoothing checked = both eyes fast blinking with off-set frames back and forth when smart smoothing kicks in.

Smart smoothing unchecked with compulsive smooth at 1/2 = works fine.
Turn on smart smoothing with compulsive at 1/2 and it kicks in with any load on the frame rate (like a passing plane).

Thank you for your amazing work!

**Comment by KCrawford100** [comment]
Just another note - the older 0.63 did not do this - I went back to SteamVR + OpenVR FSR until this morning and installed all the latest OpenXR Pimax and seems to work well except when turning on Smart Smoothing.

**Comment by mbucchia** [comment]
> Just another note - the older 0.63 did not do this - I went back to SteamVR + OpenVR FSR until this morning and installed all the latest OpenXR Pimax and seems to work well except when turning on Smart Smoothing.

I don't really understand this part.

If you went back to SteamVR, then you're not using PimaxXR.

**Comment by KCrawford100** [comment]
I am sorry, I was not clear.  I only went back for a few days to check frame rate and the settings I was using in SteamVR + OpenVR FSR vs the older 0.63 I was using before.  I have removed that and all OpenVR stuff completely and installed the latest OpenXR - Pimax.

I am running the latest DLL - Compositor - Pimax OpenXR.  That is when I discovered the smart smoothing issue.
Kindest Regards,

**Comment by KCrawford100** [comment]
PimaxXR 0.2.0
 OpenXR Toolkit GA-1(v1.14)
Latest openvr_api.dll 
Performance set to 80%

Sorry again for the confusion.

**Comment by DJSlane** [comment]
confirm, I also get the every few second blinking/incorrect pose with MR on. Specifically in DCS 
PimaxXR 0.2.0
OpenXR Toolkit GA-1(v1.14)
Latest Opencomposite system-wide

**Comment by KCrawford100** [comment]
I just installed PimaxXR 0.2.2 and I can confirm that the blinking - incorrect overlay or position still happens when using PiTool with smart smoothing enabled in DCS Open Beta.  This makes smart smoothing unusable. 

Pitool v1.0.1.279 Firmware V2.1.255.299 Pimax 8KX
i9900KS 5.2 - 3090 latest Nvidia 
PimaxXR - V0.2.2 
OpenXR Toolkit GA-1(v1.14)

**Comment by mbucchia** [comment]
I did not make any changes related to smart smoothing in 0.2.2, so I don't expect anything to have change.

Unfortunately things are working perfectly on my machine, which means there is nothing I can really do until I find a way to reproduce the problem.

**Comment by KCrawford100** [comment]
That's interesting - are your running the same Pitool firmware and Pitool version? It is almost like it is losing tracking.  

I can re-create it every time.  Try this, F-16 Instant Action (I only fly the F16) Caucasus - Offensive Basic Fighter Maneuvers.  It starts right after I pull a turn and it lasts a few seconds then stops.  I then pull another turn and it starts up again.

Pitool Settings are smart smoothing with Compulsive smooth on Close.

I can also provide my settings if that will help.  Or is there a log file I can send?

It is so much smoother with smart smoothing on with DCS.

Thanks

**Comment by KCrawford100** [comment]
Here is what it looks like with smart smoothing on.  It lasts about 10 seconds and goes away for a few seconds then comes back.

https://vimeo.com/729756900

Thanks!

**Comment by KCrawford100** [comment]
> confirm, I also get the every few second blinking/incorrect pose with MR on. Specifically in DCS PimaxXR 0.2.0 OpenXR Toolkit GA-1(v1.14) Latest Opencomposite system-wide

Have you been able to figure this problem out DJSLANE?

**Comment by DJSlane** [comment]
Yeah, but it only occurs in DCS, not in msfs2020 so I suspect this issue may be open composite or the combo of both that is the culprit.

**Comment by mbucchia** [comment]
I think this might resolve your issue. Can you please try this beta build and let me know if the issue is gone?

[PimaxXR-0.2.3c.zip](https://github.com/mbucchia/Pimax-OpenXR/files/9124777/PimaxXR-0.2.3c.zip)

Thanks!

**Comment by KCrawford100** [comment]
> I think this might resolve your issue. Can you please try this beta build and let me know if the issue is gone?
> 
> [PimaxXR-0.2.3c.zip](https://github.com/mbucchia/Pimax-OpenXR/files/9124777/PimaxXR-0.2.3c.zip)
> 
> Thanks!

You fixed the major blinking - tracking type wobble.  That has gone away - Thank you!!

There is a couple of much smaller issues:

(1) There is a slight positional stutter that looks like the images are catching up with the tracking when I turn my head.  It is hard to describe but it is more towards the sides of the image.
(2) Smart Smoothing It is not as butter smooth with the head tracking as normal (without OpenXR) and ghosting stutter of an enemy plane is more noticeable.  

This is all with compulsive smooth off, but Smart smoothing is checked.

But it is a huge improvement, thank you for your efforts!  Maybe DJSlane can be more specific.  

Again, thank you for working on this.  Anything I can do to help I am happy to do so.  I will try it with the different compulsive smooth setting and let you know.
Kindest Regards,

**Comment by KCrawford100** [comment]
Confirmed that you have removed the major blinking - wobble issue.  But, there is enough image stutter on enemy planes, head movement, or rolling the plane that running with Smart Smoothing Off is much smoother. Smart smoothing always made the rolls and head movement butter smooth.

You are on the right track, again thank you for your efforts!

**Comment by mbucchia** [comment]
Thanks. Are these other issues the result of the change in 0.2.3, or were they also in 0.2.2 (but masked by the bigger tearing issues)?

**Comment by KCrawford100** [comment]
well, honestly, I could not tell as the tearing happened frequently enough that it was all I could focus on.  but, in the morning I will reload 0.2.2 look for it best I can and let you know.

**Comment by KCrawford100** [comment]
Ok so I uninstalled 0.2.3 and re-installed 0.2.2
In between the tearing sessions I can say that the other issues are there but slightly less noticeable.

Both run much smoother with smart smoothing turned off.  Smart smoothing in the past removed all of the micro stutter that DCS seems to have but it adds a tiny bit of ghosting with high aspect passes from other planes.

I can say that 0.2.3 with smart smoothing off runs very stable.

Thanks again for the work on this.

**Comment by DJSlane** [comment]
Yep! It completely resolved it in DCS. The ghosting from high aspect passing of planes mentioned above is normal for DCS with SteamVRs motion smoothing. All aspects related to my original issue are resolved. I don't currently obeserve " image stutter on enemy planes, head movement, or rolling the plane that running with Smart Smoothing Off is much smoother. Smart smoothing always made the rolls and head movement butter smooth." as stated above. Motion smoothing in PimaxXr now appears for me just as it did in SteamVR.

**Comment by DJSlane** [comment]
Continued testing in multiple scenes. Used the hotkeys to ensure the motion smoothing on/off +/- compulsive smoothing are on/off. Yeah all aspects perform perfectly in DCS (at least as well as SteamVR did) - 

Also I triple checked ;-) Steram VR is not running and PimaxXR 2.3c is in use ;-)

**Comment by KCrawford100** [comment]
I am finding that 2.3c it is not as smooth with OpenXR as the steamVR or the OpenFSR with smart smoothing on.  I know that slight ghosting was always present, but this is something different.  Currently I will continue to run without Smart Smoothing as on my AWS server, I am getting 45-65 FPS raw which is good enough.   I just miss the ultra butter smooth Smart Smoothing gave me but it seems it is just me.
Again, Thanks!

**Comment by KCrawford100** [comment]
Just and FYI that I have tried re-installing the software, dll, compositer and I still have the same issue.  Smart Smoothing has a large stutter (large frame jump) when I turn my head side to side.  This happens if I turn my head slowly or fast.  It starts to get better then starts back up again in regular intervals.  It is butter smooth using OpenFSR or the legacy 0.63 and doesn't have the large step stutter.

I understand that I am the only one that is reporting this, and you cannot recreate it so I don't think there will be a fix any time soon but just wanted you to have it in the back of your mind if you happen to come across it again.  Luckly it is almost as smooth with all smart smoothing turned off, so I am enjoying the nice color and sharpness you have help bring to my Pimax8KX.  I am thankful for that and appreciate it.
Just for grins I will leave my sim pit PC details just in case.
i9900KS @5.2 ghz  32gig 3600 ram
3090@ OC 2.2 ghz
Pimax 8KX 
Pitool V1.0.1.280  Firmware V22.1.255.299
Tracking two V1 lighthouses

Kindest Regards,

**Comment by mbucchia** [comment]
Hey, to be clear, I don't think it's just you. At this point, smart smoothing is the last thing left to finish this project, and if you look at the other issues on github they are all related to smart smoothing. I think people just express things differently... I am actively looking into smart smoothing.

I might close this particular issue once I commit my latest changes because the original issue you reported (the tearing is fixed). But issue #12 will remain open to track the sub-optimal motion smoothing frame rate.

**Comment by DJSlane** [comment]
Makes sense. This blinking/tearing is certainly resolved.

**Comment by KCrawford100** [comment]
I agree!  and thank you for diligence on this!  The problems have to be hard with so many factors and systems.

**Comment by mbucchia** [comment]
The tearing issue was resolved in 9e8b5cf9960164552abc6991a93aa9422f628efa.

Remains performance issues with smart smoothing will be addressed in #12.
